services:
  grafana:
    user: root
    container_name: 'gcorelabs-cdn-stats-datasource'

    build:
      context: .
      args:
        grafana_image: ${GRAFANA_IMAGE:-grafana-enterprise}
        grafana_version: ${GRAFANA_VERSION:-12.1.1}
        development: ${DEVELOPMENT:-false}
        anonymous_auth_enabled: ${ANONYMOUS_AUTH_ENABLED:-true}
    ports:
      - 3000:3000/tcp
    volumes:
      - ../dist:/var/lib/grafana/plugins/gcorelabs-cdn-stats-datasource
      - ../provisioning:/etc/grafana/provisioning
      - ..:/root/gcorelabs-cdn-stats-datasource
    environment:
      NODE_ENV: development
      GF_LOG_FILTERS: plugin.gcorelabs-cdn-stats-datasource:debug
      GF_LOG_LEVEL: debug
      GF_DATAPROXY_LOGGING: 1
      GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: gcorelabs-cdn-stats-datasource
